In [4]:
import numpy as np

# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [ ]:
l = [0,1,2,3,4,5]
arr = np.array(l)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.dtype

dtype('int64')

# 2. Given a NumPy array 'arr', check if its data type is float64.

In [ ]:
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
arr.dtype

dtype('float64')

# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr = np.array([1.+0.j, 2.+0.j, 3.+0.j], np.complex128)

In [ ]:
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arr.dtype

dtype('complex128')

# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.astype("float32")

array([0., 1., 2., 3., 4., 5.], dtype=float32)

# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr = np.array([0., 1., 2., 3., 4., 5.], dtype = np.float64)
arr

array([0., 1., 2., 3., 4., 5.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.astype('float32')

array([0., 1., 2., 3., 4., 5.], dtype=float32)

# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
def array_attributes(array):
    result = [f"Shape = {array.shape}, Size = {array.size}, Data type = {array.dtype}"]
    return result

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
array_attributes(arr)

['Shape = (2, 3), Size = 6, Data type = int64']

# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(array):
    return (f"Dimension = {array.ndim}")

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
array_dimension(arr)

'Dimension = 2'

# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
def item_size_info(array):
    result = [f"Item size = {array.itemsize}, Total size = {array.nbytes}"]
    return result

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
item_size_info(arr)

['Item size = 8, Total size = 48']

# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
def array_strides(array):
    return(f"Strides = {array.strides}")

In [ ]:
arr = np.reshape(np.arange(12), (3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
array_strides(arr)

'Strides = (32, 8)'

# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
def shape_stride_relationship(array):
    result = [f"Shape = {array.shape}, Strides = {array.strides}"]
    return result

In [ ]:
arr = np.reshape(np.arange(12), (3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
shape_stride_relationship(arr)

['Shape = (3, 4), Strides = (32, 8)']

# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [ ]:
def create_zeros_array(n):
    print(f'Integer = {n}')
    return np.zeros(n)

In [ ]:
create_zeros_array(5)

Integer = 5


array([0., 0., 0., 0., 0.])

# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [ ]:
create_ones_matrix(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [ ]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [ ]:
generate_range_array(1,10,2)

array([1, 3, 5, 7, 9])

# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [ ]:
def generate_linear_space(start, stop, num):
    return np.linspace(start,stop,num)

In [ ]:
generate_linear_space(1.,10.,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
def create_identity_matrix(n):
    return np.eye(n)

In [ ]:
create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def list_to_array(List):
    return np.array(List)

In [ ]:
lst = [1,2,3,4,5,6]

In [ ]:
list_to_array(lst)

array([1, 2, 3, 4, 5, 6])

# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [ ]:
arr = np.reshape(np.arange(12), (3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
def array_concat(*array):
    return np.concatenate(array, axis = 0)

In [ ]:
arr1 = np.reshape(np.arange(1,5), (2,2))
arr2 = np.reshape(np.arange(5,9), (2,2))

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
arr2

array([[5, 6],
       [7, 8]])

In [ ]:
array_concat(arr1,arr2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [ ]:
a = np.random.randint(1,5,(3,4))
b = np.random.randint(6,10,(4,3))

In [ ]:
a

array([[4, 4, 3, 1],
       [3, 1, 4, 1],
       [4, 1, 3, 1]])

In [ ]:
b

array([[7, 7, 6],
       [8, 6, 8],
       [6, 8, 9],
       [7, 8, 6]])

In [ ]:
np.concatenate((a,b.T), axis=1)

array([[4, 4, 3, 1, 7, 8, 6, 7],
       [3, 1, 4, 1, 7, 6, 8, 8],
       [4, 1, 3, 1, 6, 8, 9, 6]])

# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
def vertically_stacks(*List):
    return np.stack((List))

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]

In [ ]:
vertically_stacks(l1,l2,l3)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
def create_array(*num):
    arr = list(range(*num))
    return np.array(arr)

In [ ]:
create_array(1,10,2)

array([1, 3, 5, 7, 9])

# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
def ten_spaced_array(*num):
    return np.linspace(*num)

In [ ]:
ten_spaced_array(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
def logarithmically_spaced(*num):
     return np.logspace(*num)

In [ ]:
logarithmically_spaced(1,1000,5)

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.




In [12]:
import pandas as pd

In [ ]:
arr = np.random.randint(1,100,(5,3))

In [ ]:
arr

array([[66, 84, 67],
       [93, 39, 63],
       [86,  7, 37],
       [32, 30, 41],
       [79, 25, 10]])

In [ ]:
pd.DataFrame(arr)

0   1   2
0  66  84  67
1  93  39  63
2  86   7  37
3  32  30  41
4  79  25  10

# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [31]:
def replace_negative(dataframe, index):
    """
    Replaces all negative values in a specific column with zeros

    Args:
        df (pd.DataFrame) : Input pandas dataframe
        index : which column has to replace with zeros

    Return:
         pd.DataFrame : Dataframe with replaces all negative values in a specific column with zeros
    """
    dataframe[index] = np.where(dataframe[index] < 0, 0, dataframe[index])
    return dataframe

In [16]:
arr = np.arange(-5,5).reshape((10,1))

In [17]:
arr

array([[-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [19]:
df = pd.DataFrame(arr)

In [20]:
df

0
0 -5
1 -4
2 -3
3 -2
4 -1
5  0
6  1
7  2
8  3
9  4

In [32]:
replace_negative(df, 0)

0
0  0
1  0
2  0
3  0
4  0
5  0
6  1
7  2
8  3
9  4

# 26. Access the 3rd element from the given NumPy array.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[2]

30

# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [34]:
arr = np.array([3, 8, 2, 10, 5, 7])

In [35]:
arr[arr > 5]

array([ 8, 10,  7])

# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:6]

array([3, 4, 5, 6])

# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
ind = np.array([0,2])

In [ ]:
arr_2d[ind]

array([[1, 2, 3],
       [7, 8, 9]])

# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.


In [36]:
def filters_elements(array, threshold):
    return array[array > threshold]

In [37]:
arr = np.random.randint(1,10,(3,2))

In [38]:
arr

array([[9, 4],
       [7, 9],
       [3, 5]])

In [39]:
filters_elements(arr, threshold = 4)

array([9, 7, 9, 5])

# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


In [ ]:
def extract_elements(array, *indices):
    return array[indices]

In [ ]:
arr_3d = np.array([[np.arange(1,10)]])

In [ ]:
arr_3d

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
index_1 = np.array([0])

In [ ]:
index_2 = np.array([0])

In [ ]:
index_3 = np.array([3])

In [ ]:
extract_elements(arr_3d, index_1,index_2,index_3)

array([4])

# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


In [ ]:
def condition_elements(array, val1, val2):
    condition = (array > val1) & (array < val2)
    return array[condition]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
condition_elements(arr, 2,8)

array([3, 4, 5, 6, 7])

# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
def extract_elements(array, rows, cols):
    return array[rows, cols]

In [ ]:
arr_2d = np.arange(1,10).reshape(3,3)

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_rows = np.array([1,2])

In [ ]:
arr_cols = np.array([1,2])

In [ ]:
extract_elements(arr_2d, arr_rows, arr_cols)

array([5, 9])

# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr = np.random.randint(1,5,(3,3))

In [ ]:
arr

array([[1, 3, 2],
       [2, 1, 3],
       [2, 1, 1]])

In [ ]:
arr + 5

array([[6, 8, 7],
       [7, 6, 8],
       [7, 6, 6]])

# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [40]:
arr1 = np.random.randint(1,5,(1,3))
arr2 = np.random.randint(1,5,(3,4))

In [41]:
arr1

array([[2, 1, 4]])

In [42]:
arr2

array([[1, 4, 1, 3],
       [4, 2, 2, 1],
       [3, 4, 1, 1]])

In [43]:
arr1.T * arr2

array([[ 2,  8,  2,  6],
       [ 4,  2,  2,  1],
       [12, 16,  4,  4]])

# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
arr1 = np.random.randint(1,5,(1,4))
arr2 = np.random.randint(1,5,(4,3))

In [ ]:
arr1

array([[4, 2, 1, 3]])

In [ ]:
arr2

array([[4, 1, 2],
       [2, 2, 4],
       [2, 4, 2],
       [3, 1, 1]])

In [ ]:
arr1.T + arr2

array([[8, 5, 6],
       [4, 4, 6],
       [3, 5, 3],
       [6, 4, 4]])

# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
arr1 = np.random.randint(1,5,(3,1))
arr2 = np.random.randint(1,5,(1,3))

In [ ]:
arr1

array([[2],
       [3],
       [4]])

In [ ]:
arr2

array([[2, 4, 1]])

In [ ]:
arr1.T + arr2

array([[4, 7, 5]])

# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
arr1 = np.random.randint(1,5,(2,3))
arr2 = np.random.randint(1,5,(2,2))

In [ ]:
arr1

array([[3, 1, 4],
       [3, 2, 2]])

In [ ]:
arr2

array([[4, 1],
       [1, 2]])

In [ ]:
try:
    arr1 * arr2
except ValueError as e:
    print("These two arrays have shape incompatibility: ",e)

These two arrays have shape incompatibility:  operands could not be broadcast together with shapes (2,3) (2,2) 


# 41. Calculate column wise mean for the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(arr, axis=1)

array([2., 5.])

# 42. Find maximum value in each row of the given array:

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
for i in range(len(arr)):
    result = np.max(arr[i])
    print(f"Maximum value of index {i} : {result}")

Maximum value of index 0 : 3
Maximum value of index 1 : 6


# 44. For the given array, apply custom function to calculate moving sum along rows.

In [10]:
def moving_sum(arr):

    moving_sums = np.cumsum(arr, axis=1)
    return moving_sums


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
result = moving_sum(arr)
print("Moving sums along rows:")
print(result)

Moving sums along rows:
[[ 1  3  6]
 [ 4  9 15]]


# 45. In the given array, check if all elements in each column are even.



In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
check_even = arr % 2 == 0
arr[check_even]

array([2, 4, 6])

# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

In [46]:
original_array = np.array([1, 2, 3, 4, 5, 6])

In [47]:
original_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
original_array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# 47. Create a function that takes a matrix as input and returns the flattened array.

In [ ]:
def flatten_array(matrix):
    return matrix.flatten()

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
flatten_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

# 48. Write a function that concatenates two given arrays along a specified axis.

In [ ]:
def concatenates(*array, axis):
    return np.concatenate(array,axis)

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [ ]:
concatenates(array1, array2.T, axis=1)

array([[1, 2, 5, 7],
       [3, 4, 6, 8]])

# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [ ]:
def splits_array(array, index):
    return np.split(array, index)

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
splits_array(original_array, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [ ]:
def insert(*insert):
    return np.insert(*insert)


def delete(*delete):
    return np.delete(*delete)


In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [ ]:
original_array

array([1, 2, 3, 4, 5])

In [ ]:
insert(original_array, indices_to_insert, values_to_insert)

array([ 1,  2, 10,  3,  4, 11,  5])

In [ ]:
delete(original_array, indices_to_delete)

array([1, 3, 5])

# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1 = np.array([ 1,  2, 10,  3,  4, 11,  5, 7, 8])
arr2 = np.arange(1,10)

In [ ]:
arr1

array([ 1,  2, 10,  3,  4, 11,  5,  7,  8])

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.add(arr1, arr2)

array([ 2,  4, 13,  7,  9, 17, 12, 15, 17])

# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
arr1 = np.arange(10,1,-1)
arr2 = np.arange(1,10)

In [ ]:
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.subtract(arr1, arr2)

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7])

# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
arr1 = np.array([ 1,  2, 10,  3])
arr2 = np.arange(1,5)

In [ ]:
arr1

array([ 1,  2, 10,  3])

In [ ]:
arr2

array([1, 2, 3, 4])

In [ ]:
np.multiply(arr1, arr2)

array([ 1,  4, 30, 12])

# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
arr1 = np.arange(2,10,2)
arr2 = np.arange(1,5)

In [ ]:
arr1

array([2, 4, 6, 8])

In [ ]:
arr2

array([1, 2, 3, 4])

In [ ]:
np.divide(arr1, arr2)

array([2., 2., 2., 2.])

# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
arr1 = np.arange(1,5)
arr2 = np.arange(5,1,-1)

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
arr2

array([5, 4, 3, 2])

In [ ]:
np.power(arr1, arr2)

array([ 1, 16, 27, 16])

# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [ ]:
def count_string(array):

    return np.char.count(array, 'hello')

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
count_string(arr)

array([1, 0, 1, 0, 1])

# 57. Write a function that extracts uppercase characters from a NumPy array of strings.



In [ ]:
def extract_upper(array):
   a = []
   for i in arr:
      for char in i:
        if np.char.isupper(char):
              a.append(char)
   return a

In [ ]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
extract_upper(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [ ]:
def replaces(array, new):
  for i, new_str in zip(array, new):
    result = np.char.replace(array, i, new_str)
  return result

In [ ]:
arr = np.array(['apple','banana', 'grape', 'pineapple'])
arr

array(['apple', 'banana', 'grape', 'pineapple'], dtype='<U9')

In [ ]:
arr_new = np.array(['Watermelon'])
arr_new

array(['Watermelon'], dtype='<U10')

In [ ]:
replaces(arr, arr_new)

array(['Watermelon', 'banana', 'grape', 'pineWatermelon'], dtype='<U14')

# 59. Write a function that concatenates strings in a NumPy array element-wise.

In [ ]:
def str_concatenate(*array):
    return np.concatenate(array)

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
str_concatenate(arr1,arr2)

array(['Hello', 'World', 'Open', 'AI'], dtype='<U5')

# 60. Write a function that finds the length of the longest string in a NumPy array.

In [ ]:
def longest_str(array):
   longest_string = max(array, key=len)
   return f'The longest string is "{longest_string}" with the length of {len(longest_string)}'

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
longest_str(arr)

'The longest string is "pineapple" with the length of 9'

# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:
dataset = np.random.randint(1, 1000, 100)

In [ ]:
dataset

array([  6, 123, 290, 736, 110, 165, 840, 686, 142, 168, 796, 178, 575,
       972, 502, 354, 391, 970, 782,  94, 260,  82, 650, 215, 918, 674,
       577, 707, 560, 205, 145, 945, 438, 298, 827, 669,   2, 625, 654,
       487, 814, 253, 384, 667, 857, 151, 936,  90,  98, 711, 856,  12,
       291, 784, 366, 735,  90, 501, 572, 201, 818, 497, 338, 970, 712,
       153, 837, 376,  33, 924,  87,  10, 803, 866, 670,  91, 652, 424,
       447, 774, 691, 202, 541, 605, 770, 891, 267, 462, 625, 269, 446,
       435, 725, 724, 630, 833, 395,  84, 636, 669])

In [ ]:
np.mean(dataset)

495.69

In [ ]:
np.median(dataset)

521.5

In [ ]:
np.var(dataset)

83021.2139

In [ ]:
np.std(dataset)

288.1340207264668

# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
dataset = np.random.randint(1, 100, 50)

In [ ]:
dataset

array([36, 54, 27, 76, 27, 99, 45, 95, 32, 82, 86, 57, 65, 42,  9, 79, 94,
       50, 67, 16, 10, 83, 11, 67, 45, 15,  6, 83,  1, 43, 45, 26, 63, 65,
       14, 85, 70, 46, 34,  2, 98, 78, 82, 87,  6, 55, 18, 40, 76, 54])

In [ ]:
np.percentile(dataset, 25)

27.0

In [ ]:
np.percentile(dataset, 75)

77.5

# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(11,20,(3,3))

In [ ]:
arr1

array([[9, 2, 8],
       [1, 3, 4],
       [8, 5, 3]])

In [ ]:
arr2

array([[14, 17, 19],
       [11, 12, 18],
       [19, 12, 14]])

In [ ]:
np.corrcoef(arr1, arr2)

array([[ 1.        , -0.31701473,  0.244899  , -0.244899  ,  0.25581395,
         0.80583738],
       [-0.31701473,  1.        , -0.99717646,  0.99717646,  0.83576611,
        -0.81705717],
       [ 0.244899  , -0.99717646,  1.        , -1.        , -0.87463929,
         0.77145428],
       [-0.244899  ,  0.99717646, -1.        ,  1.        ,  0.87463929,
        -0.77145428],
       [ 0.25581395,  0.83576611, -0.87463929,  0.87463929,  1.        ,
        -0.36628972],
       [ 0.80583738, -0.81705717,  0.77145428, -0.77145428, -0.36628972,
         1.        ]])

# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [ ]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(11,20,(3,3))

In [ ]:
arr1

array([[9, 8, 6],
       [7, 6, 5],
       [6, 3, 4]])

In [ ]:
arr2

array([[19, 13, 17],
       [14, 14, 13],
       [13, 12, 18]])

In [ ]:
np.dot(arr1, arr2)

array([[361, 301, 365],
       [282, 235, 287],
       [208, 168, 213]])

# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
arr1 = np.arange(10,1000,50)

In [ ]:
arr1

array([ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460, 510, 560, 610,
       660, 710, 760, 810, 860, 910, 960])

In [ ]:
print(f'10th percentile: {np.percentile(arr1, 10)}\n')
print(f'50th percentile (median): {np.percentile(arr1, 50)}\n')
print(f'90th percentile: {np.percentile(arr1, 90)}\n')
print(f'First quartiles (Q1): {np.percentile(arr1, 25)}\n')
print(f'Third quartiles (Q3): {np.percentile(arr1, 75)}')

10th percentile: 105.0

50th percentile (median): 485.0

90th percentile: 865.0000000000001

First quartiles (Q1): 247.5

Third quartiles (Q3): 722.5


# 66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[[0,2],[1,2]]

array([2, 9])

In [ ]:
arr_2d[1, 2]

6

# 67. Generate a random NumPy array and sort it in ascending order.

In [ ]:
arr = np.random.randint(1,10,(3,4))

In [ ]:
arr

array([[3, 7, 6, 4],
       [9, 9, 4, 2],
       [7, 3, 8, 5]])

In [ ]:
np.sort(arr)

array([[3, 4, 6, 7],
       [2, 4, 9, 9],
       [3, 5, 7, 8]])

# 68. Filter elements >20  in the given NumPy array.

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
arr[arr > 20]

array([25, 42, 30])

# 69. Filter elements which are divisible by 3 from a given NumPy array.

In [ ]:
arr = np.array([1, 5, 8, 12, 15])

In [ ]:
arr[arr % 3 == 0]

array([12, 15])

# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [48]:
arr = np.array([10, 20, 30, 40, 50])

In [50]:
arr[arr >= 20]

array([20, 30, 40, 50])

In [ ]:
arr[arr <= 40]

array([10, 20, 30, 40])

# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
arr.dtype.byteorder

'='

# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
import sys

# Get the system endianness (little-endian or big-endian)
sys_is_le = sys.byteorder == 'little'
native_code = '<' if sys_is_le else '>'

# Create a new dtype with the opposite byte order
swapped_code = '>' if sys_is_le else '<'
swapped_dt = np.dtype(swapped_code + 'i2')

# Swap the byte order using newbyteorder()
swapped_arr = arr.astype(swapped_dt)

print("Original array:")
print(arr)
print("Swapped array:")
print(swapped_arr)


Original array:
[1 2 3]
Swapped array:
[1 2 3]


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr.dtype.byteorder == '='

True

# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [ ]:
arr1 = np.arange(1,10)

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_arr = arr1

In [ ]:
copy_arr[3] = 10

In [ ]:
arr1 # Yes, modified the copy_arr affected the arr1

array([ 1,  2,  3, 10,  5,  6,  7,  8,  9])

In [ ]:
copy_arr

array([ 1,  2,  3, 10,  5,  6,  7,  8,  9])

# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [ ]:
arr_2d = np.random.randint(1,50,(3,3))

In [ ]:
arr_2d

array([[28, 14, 46],
       [ 4,  9, 30],
       [ 4,  4, 39]])

In [ ]:
view_slice = arr_2d[0:2, 0:2]

In [ ]:
view_slice

array([[28, 14],
       [ 4,  9]])

In [ ]:
view_slice[0] = 1 # Modified the element in view_slice

In [ ]:
view_slice

array([[1, 1],
       [4, 9]])

In [ ]:
arr_2d # Changed the original matrix

array([[ 1,  1, 46],
       [ 4,  9, 30],
       [ 4,  4, 39]])

In [ ]:
view_slice[1, 1] = 23 # Modified the element in view_slice

In [ ]:
view_slice

array([[ 1,  1],
       [ 4, 23]])

In [ ]:
arr_2d # Changed the original matrix

array([[ 1,  1, 46],
       [ 4, 23, 30],
       [ 4,  4, 39]])

# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
array_a = np.reshape(np.arange(1,13),(4,3))

In [ ]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
view_b = array_a[1:3, 0:2]

In [ ]:
view_b

array([[4, 5],
       [7, 8]])

In [ ]:
view_b + 5 # broadcast the addition of 5 to view_b.

array([[ 9, 10],
       [12, 13]])

In [ ]:
array_a # No, it did alter the original array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [ ]:
orig_array = np.reshape(np.arange(1,9),(2,4))

In [ ]:
orig_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
reshape_view = orig_array.reshape(4,2)

In [ ]:
reshape_view

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
reshape_view[0] = [9, 10] # Modified an element in reshaped_view

In [ ]:
reshape_view

array([[ 9, 10],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [ ]:
orig_array # changes are reflected in the original "orig_array"

array([[ 9, 10,  3,  4],
       [ 5,  6,  7,  8]])

# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [ ]:
data = np.random.randint(1,10,(3,4))

In [ ]:
data

array([[3, 6, 9, 4],
       [8, 7, 6, 5],
       [4, 8, 7, 8]])

In [ ]:
data_copy = data[data > 5]

In [ ]:
data_copy

array([6, 9, 8, 7, 6, 8, 7, 8])

In [ ]:
data_copy[3] = 12 # Modified the element

In [ ]:
data_copy

array([ 6,  9,  8, 12,  6,  8,  7,  8])

In [ ]:
data # Not affected the original "data"

array([[3, 6, 9, 4],
       [8, 7, 6, 5],
       [4, 8, 7, 8]])

# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
matrix_a = np.random.randint(1,10,(3,3))
matrix_b = np.random.randint(1,10,(3,3))

In [ ]:
matrix_a

array([[7, 3, 6],
       [4, 7, 8],
       [6, 2, 4]])

In [ ]:
matrix_b

array([[7, 3, 9],
       [8, 7, 9],
       [4, 2, 4]])

In [ ]:
# Addition

matrix_a + matrix_b

array([[14,  6, 15],
       [12, 14, 17],
       [10,  4,  8]])

In [ ]:
# Subtraction

matrix_a - matrix_b

array([[ 0,  0, -3],
       [-4,  0, -1],
       [ 2,  0,  0]])

# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [ ]:
matrix_c = np.random.randint(1,10,(3,2))
matrix_d = np.random.randint(1,10,(2,4))

In [ ]:
matrix_c

array([[4, 6],
       [6, 2],
       [5, 6]])

In [ ]:
matrix_d

array([[5, 9, 1, 3],
       [2, 5, 6, 2]])

In [ ]:
np.dot(matrix_c, matrix_d)

array([[32, 66, 40, 24],
       [34, 64, 18, 22],
       [37, 75, 41, 27]])

# 83. Create a matrix `E` and find its transpose.

In [ ]:
matrix_e = np.random.randint(1,10,(3,2))

In [ ]:
matrix_e

array([[4, 7],
       [2, 8],
       [1, 4]])

In [ ]:
matrix_e.T

array([[4, 2, 1],
       [7, 8, 4]])

# 84. Generate a square matrix `F` and compute its determinant.

In [ ]:
matrix_f = np.random.randint(1,10,(3,3))

In [ ]:
matrix_f

array([[9, 3, 1],
       [4, 3, 6],
       [4, 8, 5]])

In [ ]:
np.linalg.det(matrix_f)

-265.00000000000017

# 85. Create a square matrix `G` and find its inverse.

In [ ]:
matrix_g = np.random.randint(1,10,(3,3))

In [ ]:
matrix_g

array([[3, 6, 8],
       [6, 7, 3],
       [7, 2, 8]])

In [ ]:
np.linalg.inv(matrix_g)

array([[-0.16233766,  0.1038961 ,  0.12337662],
       [ 0.08766234,  0.1038961 , -0.12662338],
       [ 0.12012987, -0.11688312,  0.0487013 ]])